FROM --platform=$BUILDPLATFORM ubuntu:22.04 as riscv-toolchain

# The RISCV Tool Chain dependencies (not correct... needs work...).
RUN apt update && apt install -y git autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

RUN git clone -b 2023.10.12 --depth 1 --single-branch https://github.com/riscv/riscv-gnu-toolchain

WORKDIR /riscv-gnu-toolchain
RUN ./configure --prefix=/opt/riscv
RUN make -j$(nproc) linux

