default:
	make -f Makefile.default

clean:
	make -f Makefile.default clean

gem5-fusion:
	make -f Makefile.gem5-fusion

clean-gem5-fusion:
	make -f Makefile.gem5-fusion clean

gpufs:
	make -f Makefile.gpufs

clean-gpufs:
	make -f Makefile.gpufs clean
