HIP_PATH ?= /opt/rocm
HIPCC = $(HIP_PATH)/bin/hipcc

EXECUTABLE = fw_hip.default
CPPSRC = Floyd-Warshall.cpp

OPTS = -O3 -Wno-unused-result
BIN_DIR ?= ./bin.default

all: $(BIN_DIR)/$(EXECUTABLE)

$(BIN_DIR)/$(EXECUTABLE): $(CPPSRC) parse.cpp ../graph_parser/util.cpp $(BIN_DIR)
	$(HIPCC) $(OPTS) --offload-arch=gfx900,gfx90a,gfx942 $(CXXFLAGS) parse.cpp ../graph_parser/util.cpp $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

clean:
	rm -rf $(BIN_DIR)

.PHONY: fw clean
